export type ReportTemplateId = 'executive'|'analytics'|'laboratory'|'clinical'|'academic'|'financial'|'operations'|'transaction'|'research'|'minimal';
export type ReportTemplateComposition = 'hero'|'dashboard'|'specimen'|'clinical'|'academic'|'ledger'|'ops'|'transaction'|'research'|'minimal';
export interface ReportTemplate { id: ReportTemplateId; name: string; description: string; recommended: string; composition: ReportTemplateComposition; maxRecommendedColumns: number; table: 'clean'|'grid'|'lab'|'clinical'|'academic'|'ledger'|'operations'|'transaction'|'research'|'minimal'; }
export const REPORT_TEMPLATES: ReportTemplate[] = [
{id:'executive',name:'Executive',description:'Editorial management report with a strong title block, KPI ribbon and decision-ready table.',recommended:'Business and management',composition:'hero',maxRecommendedColumns:8,table:'clean'},
{id:'analytics',name:'Data Analytics',description:'Analytical dashboard composition with KPI strip, dense grid and statistical emphasis.',recommended:'Datasets and operational analysis',composition:'dashboard',maxRecommendedColumns:12,table:'grid'},
{id:'laboratory',name:'Laboratory',description:'Scientific report composition with specimen-style metadata and structured result columns.',recommended:'Laboratories and testing',composition:'specimen',maxRecommendedColumns:7,table:'lab'},
{id:'clinical',name:'Clinical',description:'Quiet clinical document hierarchy designed for readable records and print.',recommended:'Clinics and hospitals',composition:'clinical',maxRecommendedColumns:7,table:'clinical'},
{id:'academic',name:'Academic',description:'Formal academic paper-inspired layout with restrained tables and review metadata.',recommended:'Schools, colleges and universities',composition:'academic',maxRecommendedColumns:9,table:'academic'},
{id:'financial',name:'Financial',description:'Ledger composition with compact numeric columns, totals and accounting-oriented alignment.',recommended:'Finance and accounting',composition:'ledger',maxRecommendedColumns:10,table:'ledger'},
{id:'operations',name:'Operations',description:'Operational workboard layout optimized for status, inventory, staff and logistics data.',recommended:'Operations and logistics',composition:'ops',maxRecommendedColumns:11,table:'operations'},
{id:'transaction',name:'Transaction',description:'Commercial record layout with prominent transaction identity and compact line-item tables.',recommended:'Sales and transaction records',composition:'transaction',maxRecommendedColumns:10,table:'transaction'},
{id:'research',name:'Research',description:'Technical research composition with methods-style metadata and evidence-focused tables.',recommended:'Research and technical work',composition:'research',maxRecommendedColumns:8,table:'research'},
{id:'minimal',name:'Minimal',description:'Editorial neutral layout with maximum whitespace and highly printable tables.',recommended:'General purpose',composition:'minimal',maxRecommendedColumns:10,table:'minimal'}
];
export function getReportTemplate(id: ReportTemplateId){return REPORT_TEMPLATES.find(t=>t.id===id) ?? REPORT_TEMPLATES[0];}
export function recommendReportTemplate(columns:Array<{originalName:string;dataType:string}>):ReportTemplateId{const names=columns.map(c=>c.originalName.toLowerCase()).join(' ');if(/test|result|unit|reference|sample|specimen|assay|method/.test(names))return'laboratory';if(/student|grade|course|semester|roll|subject|faculty|college|school/.test(names))return'academic';if(/patient|diagnosis|clinical|doctor|hospital|visit|medication/.test(names))return'clinical';if(/revenue|expense|profit|amount|price|cost|balance|tax|payment/.test(names))return'financial';if(/order|customer|invoice|sale|transaction|sku|product/.test(names))return'transaction';if(/experiment|hypothesis|sample|research|study|observation/.test(names))return'research';const numeric=columns.filter(c=>c.dataType==='number').length;if(numeric>=Math.max(2,columns.length*.35))return'analytics';if(/inventory|warehouse|employee|staff|shift|status|location/.test(names))return'operations';return'executive'}
